vehicleGlobal = {
  --------------------------------------------------------------------------------------------------------------------------------
  -------MOTOS
  --------------------------------------------------------------------------------------------------------------------------------
  ['avarus'] = { ['name'] = 'avarus', ['price'] = 440000, ['type'] = 'motos',  ['chest'] = '15' },
  ['bagger'] = { ['name'] = 'bagger', ['price'] = 300000, ['type'] = 'motos',  ['chest'] = '35' },
  ['bati'] = { ['name'] = 'bati', ['price'] = 370000, ['type'] = 'motos',  ['chest'] = '15' },
  ['bati2'] = { ['name'] = 'bati2', ['price'] = 50000, ['type'] = 'motos',  ['chest'] = '15' },
  ['bf400'] = { ['name'] = 'bf400', ['price'] = 450000, ['type'] = 'motos',  ['chest'] = '15' },
  ['carbonrs'] = { ['name'] = 'carbonrs', ['price'] = 370000, ['type'] = 'motos',  ['chest'] = '15' },
  ['chimera'] = { ['name'] = 'chimera', ['price'] = 345000, ['type'] = 'motos',  ['chest'] = '15' },
  ['cliffhanger'] = { ['name'] = 'cliffhanger', ['price'] = 310000, ['type'] = 'motos',  ['chest'] = '15' },
  ['daemon'] = { ['name'] = 'daemon', ['price'] = 240000, ['type'] = 'motos',  ['chest'] = '15' },
  ['daemon2'] = { ['name'] = 'daemon2', ['price'] = 200000, ['type'] = 'motos',  ['chest'] = '15' },
  ['defiler'] = { ['name'] = 'defiler', ['price'] = 460000, ['type'] = 'motos',  ['chest'] = '15' },
  ['deathbike'] = { ['name'] = 'deathbike', ['price'] = 215000, ['type'] = 'motos',  ['chest'] = '15' },
  ['deathbike2'] = { ['name'] = 'deathbike2', ['price'] = 430000, ['type'] = 'motos',  ['chest'] = '15' },
  ['deathbike3'] = { ['name'] = 'deathbike3', ['price'] = 425000, ['type'] = 'motos',  ['chest'] = '15' },
  ['diablous'] = { ['name'] = 'diablous', ['price'] = 430000, ['type'] = 'motos',  ['chest'] = '15' },
  ['diablous2'] = { ['name'] = 'diablous2', ['price'] = 460000, ['type'] = 'motos',  ['chest'] = '15' },
  ['double'] = { ['name'] = 'double', ['price'] = 370000, ['type'] = 'motos',  ['chest'] = '15' },
  ['enduro'] = { ['name'] = 'enduro', ['price'] = 195000, ['type'] = 'motos',  ['chest'] = '15' },
  ['esskey'] = { ['name'] = 'esskey', ['price'] = 320000, ['type'] = 'motos',  ['chest'] = '15' },
  ['faggio'] = { ['name'] = 'faggio', ['price'] = 15000, ['type'] = 'motos',  ['chest'] = '15' },
  ['faggio2'] = { ['name'] = 'faggio2', ['price'] = 3000, ['type'] = 'motos',  ['chest'] = '15' },
  ['faggio3'] = { ['name'] = 'faggio3', ['price'] = 10000, ['type'] = 'motos',  ['chest'] = '15' },
  ['fcr'] = { ['name'] = 'fcr', ['price'] = 195000, ['type'] = 'motos',  ['chest'] = '15' },
  ['fcr2'] = { ['name'] = 'fcr2', ['price'] = 215000, ['type'] = 'motos',  ['chest'] = '15' },
  ['gargoyle'] = { ['name'] = 'gargoyle', ['price'] = 345000, ['type'] = 'motos',  ['chest'] = '15' },
  ['hakuchou'] = { ['name'] = 'hakuchou', ['price'] = 380000, ['type'] = 'motos',  ['chest'] = '15' },
  ['hakuchou2'] = { ['name'] = 'hakuchou2', ['price'] = 550000, ['type'] = 'motos',  ['chest'] = '15' },
  ['hexer'] = { ['name'] = 'hexer', ['price'] = 250000, ['type'] = 'motos',  ['chest'] = '15' },
  ['innovation'] = { ['name'] = 'innovation', ['price'] = 285000, ['type'] = 'motos',  ['chest'] = '15' },
  ['lectro'] = { ['name'] = 'lectro', ['price'] = 380000, ['type'] = 'motos',  ['chest'] = '15' },
  ['manchez'] = { ['name'] = 'manchez', ['price'] = 355000, ['type'] = 'motos',  ['chest'] = '15' },
  ['nemesis'] = { ['name'] = 'nemesis', ['price'] = 345000, ['type'] = 'motos',  ['chest'] = '15' },
  ['nightblade'] = { ['name'] = 'nightblade', ['price'] = 415000, ['type'] = 'motos',  ['chest'] = '15' },
  ['pcj'] = { ['name'] = 'pcj', ['price'] = 230000, ['type'] = 'motos',  ['chest'] = '15' },
  ['ruffian'] = { ['name'] = 'ruffian', ['price'] = 450000, ['type'] = 'motos',  ['chest'] = '15' },
  ['ratbike'] = { ['name'] = 'ratbike', ['price'] = 185000, ['type'] = 'motos',  ['chest'] = '15' },
  ['rrocket'] = { ['name'] = 'rrocket', ['price'] = 250000, ['type'] = 'motos',  ['chest'] = '15' },
  ['sanchez'] = { ['name'] = 'sanchez', ['price'] = 185000, ['type'] = 'motos',  ['chest'] = '15' },
  ['sanchez2'] = { ['name'] = 'sanchez2', ['price'] = 195000, ['type'] = 'motos',  ['chest'] = '15' },
  ['sanctus'] = { ['name'] = 'sanctus', ['price'] = 185000, ['type'] = 'motos',  ['chest'] = '15' },
  ['shotaro'] = { ['name'] = 'shotaro', ['price'] = 10000000, ['type'] = 'motos',  ['chest'] = '15' },
  ['sovereign'] = { ['name'] = 'sovereign', ['price'] = 285000, ['type'] = 'motos',  ['chest'] = '15' },
  ['stryder'] = { ['name'] = 'stryder', ['price'] = 70000, ['type'] = 'motos',  ['chest'] = '15' },
  ['thrust'] = { ['name'] = 'thrust', ['price'] = 285000, ['type'] = 'motos',  ['chest'] = '15' },
  ['vader'] = { ['name'] = 'vader', ['price'] = 290000, ['type'] = 'motos',  ['chest'] = '15' },
  ['vindicator'] = { ['name'] = 'vindicator', ['price'] = 215000, ['type'] = 'motos',  ['chest'] = '15' },
  ['vortex'] = { ['name'] = 'vortex', ['price'] = 320000, ['type'] = 'motos',  ['chest'] = '15' },
  ['wolfsbane'] = { ['name'] = 'wolfsbane', ['price'] = 345000, ['type'] = 'motos',  ['chest'] = '15' },
  ['zombiea'] = { ['name'] = 'zombiea', ['price'] = 300000, ['type'] = 'motos',  ['chest'] = '15' },
  ['zombieb'] = { ['name'] = 'zombieb', ['price'] = 300000, ['type'] = 'motos',  ['chest'] = '15' },
  ['manchez2'] = { ['name'] = 'manchez2', ['price'] = 355000, ['type'] = 'motos',  ['chest'] = '15' },
  ['bmx'] = { ['name'] = 'bmx', ['price'] = 5000,['type'] = 'motos',  ['chest'] = '15' },
  ['cruiser'] = { ['name'] = 'cruiser', ['price'] = 5000,['type'] = 'motos',  ['chest'] = '15' },
  ['fixter'] = { ['name'] = 'fixter', ['price'] = 5000,['type'] = 'motos',  ['chest'] = '15' },
  ['scorcher'] = { ['name'] = 'scorcher', ['price'] = 5000,['type'] = 'motos',  ['chest'] = '15' },
  ['tribike'] = { ['name'] = 'tribike', ['price'] = 5000,['type'] = 'motos',  ['chest'] = '15' },
  ['tribike2'] = { ['name'] = 'tribike2', ['price'] = 5000,['type'] = 'motos',  ['chest'] = '15' },
  ['tribike3'] = { ['name'] = 'tribike3', ['price'] = 5000,['type'] = 'motos',  ['chest'] = '15' },
  --------------------------------------------------------------------------------------------------------------------------------
  -------SPORTS
  --------------------------------------------------------------------------------------------------------------------------------
  ['alpha'] = { ['name'] = 'alpha', ['price'] = 240000, ['type'] = 'sports',  ['chest'] = '60' },
  ['banshee'] = { ['name'] = 'banshee', ['price'] = 240000, ['type'] = 'sports',  ['chest'] = '65' },
  ['bestiagts'] = { ['name'] = 'bestiagts', ['price'] = 290000, ['type'] = 'sports',  ['chest'] = '65' },
  ['blista2'] = { ['name'] = 'blista2', ['price'] = 50000, ['type'] = 'sports',  ['chest'] = '65' },
  ['blista3'] = { ['name'] = 'blista3', ['price'] = 70000, ['type'] = 'sports',  ['chest'] = '65' },
  ['buffalo2'] = { ['name'] = 'buffalo2', ['price'] = 240000, ['type'] = 'sports',  ['chest'] = '65' },
  ['buffalo3'] = { ['name'] = 'buffalo3', ['price'] = 240000, ['type'] = 'sports',  ['chest'] = '65' },
  ['carbonizzare'] = { ['name'] = 'carbonizzare', ['price'] = 250000, ['type'] = 'sports',  ['chest'] = '65' },
  ['comet2'] = { ['name'] = 'comet2', ['price'] = 170000, ['type'] = 'sports',  ['chest'] = '65' },
  ['comet3'] = { ['name'] = 'comet3', ['price'] = 230000, ['type'] = 'sports',  ['chest'] = '65' },
  ['comet4'] = { ['name'] = 'comet4', ['price'] = 300000, ['type'] = 'sports',  ['chest'] = '65' },
  ['comet5'] = { ['name'] = 'comet5', ['price'] = 300000, ['type'] = 'sports',  ['chest'] = '65' },
  ['coquette'] = { ['name'] = 'coquette', ['price'] = 200000, ['type'] = 'sports',  ['chest'] = '65' },
  ['coquette4'] = { ['name'] = 'coquette4', ['price'] = 3000000, ['type'] = 'sports',  ['chest'] = '65' },
  ['drafter'] = { ['name'] = 'drafter', ['price'] = 500000, ['type'] = 'sports',  ['chest'] = '65' },
  ['deveste'] = { ['name'] = 'deveste', ['price'] = 600000, ['type'] = 'sports',  ['chest'] = '55' },
  ['elegy'] = { ['name'] = 'elegy', ['price'] = 340000, ['type'] = 'sports',  ['chest'] = '55' },
  ['elegy2'] = { ['name'] = 'elegy2', ['price'] = 375000, ['type'] = 'sports',  ['chest'] = '55' },
  ['feltzer2'] = { ['name'] = 'feltzer2', ['price'] = 185000, ['type'] = 'sports',  ['chest'] = '55' },
  ['flashgt'] = { ['name'] = 'flashgt', ['price'] = 330000, ['type'] = 'sports',  ['chest'] = '55' },
  ['furoregt'] = { ['name'] = 'furoregt', ['price'] = 525000, ['type'] = 'sports',  ['chest'] = '55' },
  ['futo'] = { ['name'] = 'futo', ['price'] = 400000, ['type'] = 'sports',  ['chest'] = '55' },
  ['gb200'] = { ['name'] = 'gb200', ['price'] = 540000, ['type'] = 'sports',  ['chest'] = '55' },
  ['hotring'] = { ['name'] = 'hotring', ['price'] = 280000, ['type'] = 'sports',  ['chest'] = '55' },
  ['komoda'] = { ['name'] = 'komoda', ['price'] = 340000, ['type'] = 'sports',  ['chest'] = '55' },
  ['imorgon'] = { ['name'] = 'imorgon', ['price'] = 580000, ['type'] = 'sports',  ['chest'] = '55' },
  ['issi7'] = { ['name'] = 'issi7', ['price'] = 530000, ['type'] = 'sports',  ['chest'] = '55' },
  ['italigto'] = { ['name'] = 'italigto', ['price'] = 330000, ['type'] = 'sports',  ['chest'] = '55' },
  ['jugular'] = { ['name'] = 'jugular', ['price'] = 650000, ['type'] = 'sports',  ['chest'] = '55' },
  ['jester'] = { ['name'] = 'jester', ['price'] = 690000, ['type'] = 'sports',  ['chest'] = '55' },
  ['jester2'] = { ['name'] = 'jester2', ['price'] = 700000, ['type'] = 'sports',  ['chest'] = '55' },
  ['jester3'] = { ['name'] = 'jester3', ['price'] = 710000, ['type'] = 'sports',  ['chest'] = '55' },
  ['khamelion'] = { ['name'] = 'khamelion', ['price'] = 220000, ['type'] = 'sports',  ['chest'] = '55' },
  ['kuruma'] = { ['name'] = 'kuruma', ['price'] = 280000, ['type'] = 'sports',  ['chest'] = '55' },
  ['locust'] = { ['name'] = 'locust', ['price'] = 450000, ['type'] = 'sports',  ['chest'] = '55' },
  ['lynx'] = { ['name'] = 'lynx', ['price'] = 290000, ['type'] = 'sports',  ['chest'] = '55' },
  ['massacro'] = { ['name'] = 'massacro', ['price'] = 320000, ['type'] = 'sports',  ['chest'] = '55' },
  ['massacro2'] = { ['name'] = 'massacro2', ['price'] = 325000, ['type'] = 'sports',  ['chest'] = '55' },
  ['neo'] = { ['name'] = 'neo', ['price'] = 300000, ['type'] = 'sports',  ['chest'] = '55' },
  ['neon'] = { ['name'] = 'neon', ['price'] = 300000, ['type'] = 'sports',  ['chest'] = '55' },
  ['ninef'] = { ['name'] = 'ninef', ['price'] = 440000, ['type'] = 'sports',  ['chest'] = '55' },
  ['ninef2'] = { ['name'] = 'ninef2', ['price'] = 460000, ['type'] = 'sports',  ['chest'] = '55' },
  ['omnis'] = { ['name'] = 'omnis', ['price'] = 335000, ['type'] = 'sports',  ['chest'] = '55' },
  ['paragon'] = { ['name'] = 'paragon', ['price'] = 290000, ['type'] = 'sports',  ['chest'] = '55' },
  ['paragon2'] = { ['name'] = 'paragon2', ['price'] = 315000, ['type'] = 'sports',  ['chest'] = '55' },
  ['pariah'] = { ['name'] = 'pariah', ['price'] = 700000, ['type'] = 'sports',  ['chest'] = '55' },
  ['penumbra'] = { ['name'] = 'penumbra', ['price'] = 340000, ['type'] = 'sports',  ['chest'] = '55' },
  ['penumbra2'] = { ['name'] = 'penumbra2', ['price'] = 355000, ['type'] = 'sports',  ['chest'] = '55' },
  ['raiden'] = { ['name'] = 'raiden', ['price'] = 210000, ['type'] = 'sports',  ['chest'] = '55' },
  ['rapidgt'] = { ['name'] = 'rapidgt', ['price'] = 290000, ['type'] = 'sports',  ['chest'] = '55' },
  ['rapidgt2'] = { ['name'] = 'rapidgt2', ['price'] = 315000, ['type'] = 'sports',  ['chest'] = '55' },
  ['raptor'] = { ['name'] = 'raptor', ['price'] = 240000, ['type'] = 'sports',  ['chest'] = '55' },
  ['revolter'] = { ['name'] = 'revolter', ['price'] = 220000, ['type'] = 'sports',  ['chest'] = '55' },
  ['ruston'] = { ['name'] = 'ruston', ['price'] = 490000, ['type'] = 'sports',  ['chest'] = '55' },
  ['schafter2'] = { ['name'] = 'schafter2', ['price'] = 420000, ['type'] = 'sports',  ['chest'] = '55' },
  ['schafter3'] = { ['name'] = 'schafter3', ['price'] = 290000, ['type'] = 'sports',  ['chest'] = '55' },
  ['schafter4'] = { ['name'] = 'schafter4', ['price'] = 310000, ['type'] = 'sports',  ['chest'] = '55' },
  ['schlagen'] = { ['name'] = 'schlagen', ['price'] = 600000, ['type'] = 'sports',  ['chest'] = '55' },
  ['schwarzer'] = { ['name'] = 'schwarzer', ['price'] = 400000, ['type'] = 'sports',  ['chest'] = '55' },
  ['sentinel3'] = { ['name'] = 'sentinel3', ['price'] = 190000, ['type'] = 'sports',  ['chest'] = '55' },
  ['seven70'] = { ['name'] = 'seven70', ['price'] = 300000, ['type'] = 'sports',  ['chest'] = '55' },
  ['specter'] = { ['name'] = 'specter', ['price'] = 350000, ['type'] = 'sports',  ['chest'] = '55' },
  ['specter2'] = { ['name'] = 'specter2', ['price'] = 380000, ['type'] = 'sports',  ['chest'] = '55' },
  ['streiter'] = { ['name'] = 'streiter', ['price'] = 280000, ['type'] = 'sports',  ['chest'] = '55' },
  ['sugoi'] = { ['name'] = 'sugoi', ['price'] = 320000, ['type'] = 'sports',  ['chest'] = '55' },
  ['sultan'] = { ['name'] = 'sultan', ['price'] = 180000, ['type'] = 'sports',  ['chest'] = '55' },
  ['sultan2'] = { ['name'] = 'sultan2', ['price'] = 580000, ['type'] = 'sports',  ['chest'] = '55' },
  ['surano'] = { ['name'] = 'surano', ['price'] = 290000, ['type'] = 'sports',  ['chest'] = '55' },
  ['tampa2'] = { ['name'] = 'tampa2', ['price'] = 200000, ['type'] = 'sports',  ['chest'] = '55' },
  ['tropos'] = { ['name'] = 'tropos', ['price'] = 190000, ['type'] = 'sports',  ['chest'] = '55' },
  ['verlierer2'] = { ['name'] = 'verlierer2', ['price'] = 300000, ['type'] = 'sports',  ['chest'] = '55' },
  ['vstr'] = { ['name'] = 'vstr', ['price'] = 600000, ['type'] = 'sports',  ['chest'] = '55' },
  ['italirsx'] = { ['name'] = 'italirsx', ['price'] = 1500000, ['type'] = 'sports',  ['chest'] = '55' },
  ['veto'] = { ['name'] = 'veto', ['price'] = 310000, ['type'] = 'sports',  ['chest'] = '55' },
  ['veto2'] = { ['name'] = 'veto2', ['price'] = 320000, ['type'] = 'sports',  ['chest'] = '55' },
  ['zr350'] = { ['name'] = 'zr350', ['price'] = 320000, ['type'] = 'sports',  ['chest'] = '55' },
  ['calico'] = { ['name'] = 'calico', ['price'] = 35000, ['type'] = 'sports',  ['chest'] = '55' },
  ['futo2'] = { ['name'] = 'futo2', ['price'] = 285000, ['type'] = 'sports',  ['chest'] = '55' },
  ['euros'] = { ['name'] = 'euros', ['price'] = 300000, ['type'] = 'sports',  ['chest'] = '55' },
  ['jester4'] = { ['name'] = 'jester4', ['price'] = 85000, ['type'] = 'sports',  ['chest'] = '55' },
  ['remus'] = { ['name'] = 'remus', ['price'] = 400000, ['type'] = 'sports',  ['chest'] = '55' },
  ['growler'] = { ['name'] = 'growler', ['price'] = 320000, ['type'] = 'sports',  ['chest'] = '55' },
  ['vectre'] = { ['name'] = 'vectre', ['price'] = 285000, ['type'] = 'sports',  ['chest'] = '55' },
  ['cypher'] = { ['name'] = 'cypher', ['price'] = 50000, ['type'] = 'sports',  ['chest'] = '55' },
  ['sultan3'] = { ['name'] = 'sultan3', ['price'] = 85000, ['type'] = 'sports',  ['chest'] = '55' },
  ['rt3000'] = { ['name'] = 'rt3000', ['price'] = 200000, ['type'] = 'sports',  ['chest'] = '65' },
  ['adder'] = { ['name'] = 'adder', ['price'] = 320000, ['type'] = 'sports',  ['chest'] = '70' },
  ['autarch'] = { ['name'] = 'autarch', ['price'] = 80000, ['type'] = 'sports',  ['chest'] = '70' },
  ['banshee2'] = { ['name'] = 'banshee2', ['price'] = 120000, ['type'] = 'sports',  ['chest'] = '70' },
  ['bullet'] = { ['name'] = 'bullet', ['price'] = 240000, ['type'] = 'sports',  ['chest'] = '70' },
  ['cheetah'] = { ['name'] = 'cheetah', ['price'] = 230000, ['type'] = 'sports',  ['chest'] = '70' },
  ['cyclone'] = { ['name'] = 'cyclone', ['price'] = 280000, ['type'] = 'sports',  ['chest'] = '70' },
  ['entity2'] = { ['name'] = 'entity2', ['price'] = 240000, ['type'] = 'sports',  ['chest'] = '70' },
  ['entityxf'] = { ['name'] = 'entityxf', ['price'] = 280000, ['type'] = 'sports',  ['chest'] = '70' },
  ['emerus'] = { ['name'] = 'emerus', ['price'] = 300000, ['type'] = 'sports',  ['chest'] = '70' },
  ['fmj'] = { ['name'] = 'fmj', ['price'] = 320000, ['type'] = 'sports',  ['chest'] = '70' },
  ['furia'] = { ['name'] = 'furia', ['price'] = 400000, ['type'] = 'sports',  ['chest'] = '70' },
  ['gp1'] = { ['name'] = 'gp1', ['price'] = 130000, ['type'] = 'sports',  ['chest'] = '70' },
  ['infernus'] = { ['name'] = 'infernus', ['price'] = 180000, ['type'] = 'sports',  ['chest'] = '70' },
  ['italigtb'] = { ['name'] = 'italigtb', ['price'] = 190000, ['type'] = 'sports',  ['chest'] = '70' },
  ['italigtb2'] = { ['name'] = 'italigtb2', ['price'] = 200000, ['type'] = 'sports',  ['chest'] = '70' },
  ['krieger'] = { ['name'] = 'krieger', ['price'] = 280000, ['type'] = 'sports',  ['chest'] = '70' },
  ['le7b'] = { ['name'] = 'le7b', ['price'] = 300000, ['type'] = 'sports',  ['chest'] = '70' },
  ['nero'] = { ['name'] = 'nero', ['price'] = 340000, ['type'] = 'sports',  ['chest'] = '70' },
  ['nero2'] = { ['name'] = 'nero2', ['price'] = 280000, ['type'] = 'sports',  ['chest'] = '70' },
  ['osiris'] = { ['name'] = 'osiris', ['price'] = 250000, ['type'] = 'sports',  ['chest'] = '70' },
  ['penetrator'] = { ['name'] = 'penetrator', ['price'] = 210000, ['type'] = 'sports',  ['chest'] = '70' },
  ['pfister811'] = { ['name'] = 'pfister811', ['price'] = 280000, ['type'] = 'sports',  ['chest'] = '70' },
  ['prototipo'] = { ['name'] = 'prototipo', ['price'] = 400000, ['type'] = 'sports',  ['chest'] = '70' },
  ['reaper'] = { ['name'] = 'reaper', ['price'] = 300000, ['type'] = 'sports',  ['chest'] = '70' },
  ['s80'] = { ['name'] = 's80', ['price'] = 220000, ['type'] = 'sports',  ['chest'] = '70' },
  ['sc1'] = { ['name'] = 'sc1', ['price'] = 280000, ['type'] = 'sports',  ['chest'] = '70' },
  ['sheava'] = { ['name'] = 'sheava', ['price'] = 60000, ['type'] = 'sports',  ['chest'] = '70' },
  ['sultanrs'] = { ['name'] = 'sultanrs', ['price'] = 750000, ['type'] = 'sports',  ['chest'] = '70' },
  ['t20'] = { ['name'] = 't20', ['price'] = 400000, ['type'] = 'sports',  ['chest'] = '70' },
  ['taipan'] = { ['name'] = 'taipan', ['price'] = 600000, ['type'] = 'sports',  ['chest'] = '70' },
  ['tempesta'] = { ['name'] = 'tempesta', ['price'] = 400000, ['type'] = 'sports',  ['chest'] = '70' },
  ['tezeract'] = { ['name'] = 'tezeract', ['price'] = 70000, ['type'] = 'sports',  ['chest'] = '70' },
  ['thrax'] = { ['name'] = 'thrax', ['price'] = 400000, ['type'] = 'sports',  ['chest'] = '70' },
  ['tigon'] = { ['name'] = 'tigon', ['price'] = 720099, ['type'] = 'sports',  ['chest'] = '70' },
  ['turismor'] = { ['name'] = 'turismor', ['price'] = 400000, ['type'] = 'sports',  ['chest'] = '70' },
  ['tyrant'] = { ['name'] = 'tyrant', ['price'] = 500000, ['type'] = 'sports',  ['chest'] = '70' },
  ['tyrus'] = { ['name'] = 'tyrus', ['price'] = 700000, ['type'] = 'sports',  ['chest'] = '70' },
  ['vacca'] = { ['name'] = 'vacca', ['price'] = 650000, ['type'] = 'sports',  ['chest'] = '70' },
  ['vagner'] = { ['name'] = 'vagner', ['price'] = 2000000, ['type'] = 'sports',  ['chest'] = '70' },
  ['visione'] = { ['name'] = 'visione', ['price'] = 280000, ['type'] = 'sports',  ['chest'] = '70' },
  ['voltic'] = { ['name'] = 'voltic', ['price'] = 300000, ['type'] = 'sports',  ['chest'] = '70' },
  ['xa21'] = { ['name'] = 'xa21', ['price'] = 650000, ['type'] = 'sports',  ['chest'] = '70' },
  ['zentorno'] = { ['name'] = 'zentorno', ['price'] = 600000, ['type'] = 'sports',  ['chest'] = '70' },
  ['zorrusso'] = { ['name'] = 'zorrusso', ['price'] = 145000, ['type'] = 'sports',  ['chest'] = '60' },
  --------------------------------------------------------------------------------------------------------------------------------
  -------classic_sports
  --------------------------------------------------------------------------------------------------------------------------------
  ['ardent'] = { ['name'] = 'ardent', ['price'] = 200000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['btype'] = { ['name'] = 'btype', ['price'] = 250000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['btype2'] = { ['name'] = 'btype2', ['price'] = 230000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['btype3'] = { ['name'] = 'btype3', ['price'] = 100000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['casco'] = { ['name'] = 'casco', ['price'] = 250000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['cheetah2'] = { ['name'] = 'cheetah2', ['price'] = 180000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['coquette2'] = { ['name'] = 'coquette2', ['price'] = 1500000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['dynasty'] = { ['name'] = 'dynasty', ['price'] = 85000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['fagaloa'] = { ['name'] = 'fagaloa', ['price'] = 180000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['feltzer3'] = { ['name'] = 'feltzer3', ['price'] = 100000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['gt500'] = { ['name'] = 'gt500', ['price'] = 500000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['infernus2'] = { ['name'] = 'infernus2', ['price'] = 1500000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['jb700'] = { ['name'] = 'jb700', ['price'] = 1500000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['jb7002'] = { ['name'] = 'jb7002', ['price'] = 285000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['mamba'] = { ['name'] = 'mamba', ['price'] = 15000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['manana'] = { ['name'] = 'manana', ['price'] = 25000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['manana2'] = { ['name'] = 'manana2', ['price'] = 30000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['michelli'] = { ['name'] = 'michelli', ['price'] = 70000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['monroe'] = { ['name'] = 'monroe', ['price'] = 40000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['nebula'] = { ['name'] = 'nebula', ['price'] = 30000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['peyote'] = { ['name'] = 'peyote', ['price'] = 35000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['peyote3'] = { ['name'] = 'peyote3', ['price'] = 40000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['pigalle'] = { ['name'] = 'pigalle', ['price'] = 80000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['rapidgt3'] = { ['name'] = 'rapidgt3', ['price'] = 45000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['retinue'] = { ['name'] = 'retinue', ['price'] = 50000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['retinue2'] = { ['name'] = 'retinue2', ['price'] = 80000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['savestra'] = { ['name'] = 'savestra', ['price'] = 80000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['stinger'] = { ['name'] = 'stinger', ['price'] = 100000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['stingergt'] = { ['name'] = 'stingergt', ['price'] = 120000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['swinger'] = { ['name'] = 'swinger', ['price'] = 15000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['tornado2'] = { ['name'] = 'tornado2', ['price'] = 20000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['tornado3'] = { ['name'] = 'tornado3', ['price'] = 12000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['tornado4'] = { ['name'] = 'tornado4', ['price'] = 20000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['tornado5'] = { ['name'] = 'tornado5', ['price'] = 15000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['tornado6'] = { ['name'] = 'tornado6', ['price'] = 110000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['turismo2'] = { ['name'] = 'turismo2', ['price'] = 200000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['viseris'] = { ['name'] = 'viseris', ['price'] = 130000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['z190'] = { ['name'] = 'z190', ['price'] = 200000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['ztype'] = { ['name'] = 'ztype', ['price'] = 57000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['zion3'] = { ['name'] = 'zion3', ['price'] = 40000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  ['cheburek'] = { ['name'] = 'cheburek', ['price'] = 80000, ['type'] = 'classic_sports',  ['chest'] = '65' },
  --------------------------------------------------------------------------------------------------------------------------------
  -------COMPACT
  --------------------------------------------------------------------------------------------------------------------------------
  ['asbo'] = { ['name'] = 'asbo', ['price'] = 145000, ['type'] = 'compact',  ['chest'] = '60' },
  ['brioso'] = { ['name'] = 'brioso', ['price'] = 145000, ['type'] = 'compact',  ['chest'] = '60' },
  ['club'] = { ['name'] = 'club', ['price'] = 50000, ['type'] = 'compact',  ['chest'] = '60' },
  ['dilettante'] = { ['name'] = 'dilettante', ['price'] = 40000, ['type'] = 'compact',  ['chest'] = '60' },
  ['kanjo'] = { ['name'] = 'kanjo', ['price'] = 30000, ['type'] = 'compact',  ['chest'] = '60' },
  ['issi2'] = { ['name'] = 'issi2', ['price'] = 20000, ['type'] = 'compact',  ['chest'] = '60' },
  ['issi3'] = { ['name'] = 'issi3', ['price'] = 40000, ['type'] = 'compact',  ['chest'] = '60' },
  ['issi4'] = { ['name'] = 'issi4', ['price'] = 40000, ['type'] = 'compact',  ['chest'] = '60' },
  ['issi5'] = { ['name'] = 'issi5', ['price'] = 50000, ['type'] = 'compact',  ['chest'] = '60' },
  ['issi6'] = { ['name'] = 'issi6', ['price'] = 5000, ['type'] = 'compact',  ['chest'] = '60' },
  ['panto'] = { ['name'] = 'panto', ['price'] = 10000, ['type'] = 'compact',  ['chest'] = '60' },
  ['rhapsody'] = { ['name'] = 'rhapsody', ['price'] = 30000, ['type'] = 'compact',  ['chest'] = '60' },
  ['brioso2'] = { ['name'] = 'brioso2', ['price'] = 12000, ['type'] = 'compact',  ['chest'] = '60' },
  ['weevil'] = { ['name'] = 'weevil', ['price'] = 100000, ['type'] = 'compact',  ['chest'] = '60' },
  ['cogcabrio'] = { ['name'] = 'cogcabrio', ['price'] = 100000, ['type'] = 'compact',  ['chest'] = '60' },
  ['exemplar'] = { ['name'] = 'exemplar', ['price'] = 100000, ['type'] = 'compact',  ['chest'] = '60' },
  ['f620'] = { ['name'] = 'f620', ['price'] = 100000, ['type'] = 'compact',  ['chest'] = '60' },
  ['felon'] = { ['name'] = 'felon', ['price'] = 100000, ['type'] = 'compact',  ['chest'] = '60' },
  ['felon2'] = { ['name'] = 'felon2', ['price'] = 100000, ['type'] = 'compact',  ['chest'] = '60' },
  ['jackal'] = { ['name'] = 'jackal', ['price'] = 100000, ['type'] = 'compact',  ['chest'] = '60' },
  ['zion2'] = { ['name'] = 'zion2', ['price'] = 100000, ['type'] = 'compact',  ['chest'] = '60' },
  ['previon'] = { ['name'] = 'previon', ['price'] = 15000, ['type'] = 'compact',  ['chest'] = '70' },
  --------------------------------------------------------------------------------------------------------------------------------
  -------OFF-ROAD
  --------------------------------------------------------------------------------------------------------------------------------
  ['bfinjection'] = { ['name'] = 'bfinjection', ['price'] = 20000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['bifta'] = { ['name'] = 'bifta', ['price'] = 20000, ['type'] = 'off_road',  ['chest'] = '30' },
  ['blazer'] = { ['name'] = 'blazer', ['price'] = 25000, ['type'] = 'off_road',  ['chest'] = '30' },
  ['blazer3'] = { ['name'] = 'blazer3', ['price'] = 30000, ['type'] = 'off_road',  ['chest'] = '30' },
  ['blazer4'] = { ['name'] = 'blazer4', ['price'] = 15000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['bodhi2'] = { ['name'] = 'bodhi2', ['price'] = 50000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['brawler'] = { ['name'] = 'brawler', ['price'] = 2000000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['bruiser'] = { ['name'] = 'bruiser', ['price'] = 2000000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['bruiser2'] = { ['name'] = 'bruiser2', ['price'] = 2000000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['bruiser3'] = { ['name'] = 'bruiser3', ['price'] = 100000, ['type'] = 'off_road',  ['chest'] = '90' },
  ['brutus'] = { ['name'] = 'brutus', ['price'] = 200000, ['type'] = 'off_road',  ['chest'] = '90' },
  ['brutus2'] = { ['name'] = 'brutus2', ['price'] = 300000, ['type'] = 'off_road',  ['chest'] = '90' },
  ['brutus3'] = { ['name'] = 'brutus3', ['price'] = 200000, ['type'] = 'off_road',  ['chest'] = '90' },
  ['caracara2'] = { ['name'] = 'caracara2', ['price'] = 25000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['dloader'] = { ['name'] = 'dloader', ['price'] = 180000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['dubsta3'] = { ['name'] = 'dubsta3', ['price'] = 40000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['dune'] = { ['name'] = 'dune', ['price'] = 200000, ['type'] = 'off_road',  ['chest'] = '80' },
  ['everon'] = { ['name'] = 'everon', ['price'] = 130000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['freecrawler'] = { ['name'] = 'freecrawler', ['price'] = 30000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['kalahari'] = { ['name'] = 'kalahari', ['price'] = 90000, ['type'] = 'off_road',  ['chest'] = '120' },
  ['kamacho'] = { ['name'] = 'kamacho', ['price'] = 500000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['marshall'] = { ['name'] = 'marshall', ['price'] = 80000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['mesa3'] = { ['name'] = 'mesa3', ['price'] = 1000000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['monster'] = { ['name'] = 'monster', ['price'] = 1000000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['monster3'] = { ['name'] = 'monster3', ['price'] = 1000000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['monster4'] = { ['name'] = 'monster4', ['price'] = 1000000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['monster5'] = { ['name'] = 'monster5', ['price'] = 50000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['outlaw'] = { ['name'] = 'outlaw', ['price'] = 50000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['rancherxl'] = { ['name'] = 'rancherxl', ['price'] = 30000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['rebel'] = { ['name'] = 'rebel', ['price'] = 50000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['rebel2'] = { ['name'] = 'rebel2', ['price'] = 70000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['riata'] = { ['name'] = 'riata', ['price'] = 82000, ['type'] = 'off_road',  ['chest'] = '120' },
  ['sandking'] = { ['name'] = 'sandking', ['price'] = 120000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['sandking2'] = { ['name'] = 'sandking2', ['price'] = 130000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['trophytruck'] = { ['name'] = 'trophytruck', ['price'] = 70000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['trophytruck2'] = { ['name'] = 'trophytruck2', ['price'] = 70000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['vagrant'] = { ['name'] = 'vagrant', ['price'] = 30000, ['type'] = 'off_road',  ['chest'] = '70' },
  ['verus'] = { ['name'] = 'verus', ['price'] = 250000, ['type'] = 'off_road',  ['chest'] = '2000' },
  ['winky'] = { ['name'] = 'winky', ['price'] = 145000, ['type'] = 'off_road',  ['chest'] = '150' },
  ['guardian'] = { ['name'] = 'guardian', ['price'] = 120000, ['type'] = 'off_road',  ['chest'] = '100' },
  ['baller'] = { ['name'] = 'baller', ['price'] = 300000, ['type'] = 'off_road',  ['chest'] = '100' },
  ['sadler'] = { ['name'] = 'sadler', ['price'] = 100000, ['type'] = 'off_road',  ['chest'] = '180' },
  ['bison'] = { ['name'] = 'bison', ['price'] = 75000, ['type'] = 'off_road',  ['chest'] = '180' },
  ['bison2'] = { ['name'] = 'bison2', ['price'] = 75000, ['type'] = 'off_road',  ['chest'] = '180' },
  ['bison3'] = { ['name'] = 'bison3', ['price'] = 75000, ['type'] = 'off_road',  ['chest'] = '180' },
  ['bobcatxl'] = { ['name'] = 'bobcatxl', ['price'] = 75000, ['type'] = 'off_road',  ['chest'] = '180' },
  ['tractor2'] = { ['name'] = 'tractor2', ['price'] = 80000, ['type'] = 'off_road',  ['chest'] = '15' },
  --------------------------------------------------------------------------------------------------------------------------------
  -------SUV
  --------------------------------------------------------------------------------------------------------------------------------
  ['baller2'] = { ['name'] = 'baller2', ['price'] = 300000, ['type'] = 'suv',  ['chest'] = '100' },
  ['baller3'] = { ['name'] = 'baller3', ['price'] = 10000, ['type'] = 'suv',  ['chest'] = '100' },
  ['baller4'] = { ['name'] = 'baller4', ['price'] = 40000, ['type'] = 'suv',  ['chest'] = '100' },
  ['bjxl'] = { ['name'] = 'bjxl', ['price'] = 50000, ['type'] = 'suv',  ['chest'] = '100' },
  ['cavalcade'] = { ['name'] = 'cavalcade', ['price'] = 100000, ['type'] = 'suv',  ['chest'] = '100' },
  ['cavalcade2'] = { ['name'] = 'cavalcade2', ['price'] = 100000, ['type'] = 'suv',  ['chest'] = '100' },
  ['contender'] = { ['name'] = 'contender', ['price'] = 120000, ['type'] = 'suv',  ['chest'] = '100' },
  ['dubsta'] = { ['name'] = 'dubsta', ['price'] = 80000, ['type'] = 'suv',  ['chest'] = '100' },
  ['dubsta2'] = { ['name'] = 'dubsta2', ['price'] = 60000, ['type'] = 'suv',  ['chest'] = '100' },
  ['fq2'] = { ['name'] = 'fq2', ['price'] = 50000, ['type'] = 'suv',  ['chest'] = '100' },
  ['granger'] = { ['name'] = 'granger', ['price'] = 40000, ['type'] = 'suv',  ['chest'] = '100' },
  ['gresley'] = { ['name'] = 'gresley', ['price'] = 50000, ['type'] = 'suv',  ['chest'] = '100' },
  ['habanero'] = { ['name'] = 'habanero', ['price'] = 40000, ['type'] = 'suv',  ['chest'] = '100' },
  ['huntley'] = { ['name'] = 'huntley', ['price'] = 60000, ['type'] = 'suv',  ['chest'] = '100' },
  ['landstalker'] = { ['name'] = 'landstalker', ['price'] = 50000, ['type'] = 'suv',  ['chest'] = '100' },
  ['landstalker2'] = { ['name'] = 'landstalker2', ['price'] = 120000, ['type'] = 'suv',  ['chest'] = '100' },
  ['mesa'] = { ['name'] = 'mesa', ['price'] = 50000, ['type'] = 'suv',  ['chest'] = '100' },
  ['novak'] = { ['name'] = 'novak', ['price'] = 100000, ['type'] = 'suv',  ['chest'] = '100' },
  ['patriot'] = { ['name'] = 'patriot', ['price'] = 30000, ['type'] = 'suv',  ['chest'] = '100' },
  ['patriot2'] = { ['name'] = 'patriot2', ['price'] = 90000, ['type'] = 'suv',  ['chest'] = '100' },
  ['radi'] = { ['name'] = 'radi', ['price'] = 40000, ['type'] = 'suv',  ['chest'] = '100' },
  ['rebla'] = { ['name'] = 'rebla', ['price'] = 35000, ['type'] = 'suv',  ['chest'] = '100' },
  ['rocoto'] = { ['name'] = 'rocoto', ['price'] = 30000, ['type'] = 'suv',  ['chest'] = '100' },
  ['seminole'] = { ['name'] = 'seminole', ['price'] = 40000, ['type'] = 'suv',  ['chest'] = '100' },
  ['seminole2'] = { ['name'] = 'seminole2', ['price'] = 200000, ['type'] = 'suv',  ['chest'] = '100' },
  ['serrano'] = { ['name'] = 'serrano', ['price'] = 120000, ['type'] = 'suv',  ['chest'] = '100' },
  ['toros'] = { ['name'] = 'toros', ['price'] = 500000, ['type'] = 'suv',  ['chest'] = '100' },
  ['xls'] = { ['name'] = 'xls', ['price'] = 20000, ['type'] = 'suv',  ['chest'] = '60' },
  --------------------------------------------------------------------------------------------------------------------------------
  -------SEDAN
  --------------------------------------------------------------------------------------------------------------------------------
  ['asea'] = { ['name'] = 'asea', ['price'] = 40000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['asterope'] = { ['name'] = 'asterope', ['price'] = 60000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['cog55'] = { ['name'] = 'cog55', ['price'] = 20000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['cognoscenti'] = { ['name'] = 'cognoscenti', ['price'] = 10000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['emperor'] = { ['name'] = 'emperor', ['price'] = 20000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['fugitive'] = { ['name'] = 'fugitive', ['price'] = 20000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['glendale'] = { ['name'] = 'glendale', ['price'] = 30000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['glendale2'] = { ['name'] = 'glendale2', ['price'] = 40000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['intruder'] = { ['name'] = 'intruder', ['price'] = 25000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['premier'] = { ['name'] = 'premier', ['price'] = 45000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['primo'] = { ['name'] = 'primo', ['price'] = 90000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['primo2'] = { ['name'] = 'primo2', ['price'] = 40000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['regina'] = { ['name'] = 'regina', ['price'] = 10000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['romero'] = { ['name'] = 'romero', ['price'] = 100000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['stafford'] = { ['name'] = 'stafford', ['price'] = 50000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['stanier'] = { ['name'] = 'stanier', ['price'] = 50000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['stratum'] = { ['name'] = 'stratum', ['price'] = 50000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['stretch'] = { ['name'] = 'stretch', ['price'] = 40000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['superd'] = { ['name'] = 'superd', ['price'] = 40000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['surge'] = { ['name'] = 'surge', ['price'] = 150000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['tailgater'] = { ['name'] = 'tailgater', ['price'] = 36000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['warrener'] = { ['name'] = 'warrener', ['price'] = 7000, ['type'] = 'sedan',  ['chest'] = '60' },
  ['washington'] = { ['name'] = 'washington', ['price'] = 75000, ['type'] = 'sedan',  ['chest'] = '10' },
  ['tailgater2'] = { ['name'] = 'tailgater2', ['price'] = 35000, ['type'] = 'sedan',  ['chest'] = '15' },
  --------------------------------------------------------------------------------------------------------------------------------
  -------VANS
  --------------------------------------------------------------------------------------------------------------------------------
  ['mule'] = { ['name'] = 'mule', ['price'] = 1000000, ['type'] = 'vans',  ['chest'] = '250' },
  ['mule2'] = { ['name'] = 'mule2', ['price'] = 1200000, ['type'] = 'vans',  ['chest'] = '340' },
  ['mule3'] = { ['name'] = 'mule3', ['price'] = 1400000, ['type'] = 'vans',  ['chest'] = '420' },
  ['boxville'] = { ['name'] = 'boxville', ['price'] = 260000, ['type'] = 'vans',  ['chest'] = '180' },
  ['boxville2'] = { ['name'] = 'boxville2', ['price'] = 260000, ['type'] = 'vans',  ['chest'] = '180' },
  ['boxville3'] = { ['name'] = 'boxville3', ['price'] = 260000, ['type'] = 'vans',  ['chest'] = '180' },
  ['boxville4'] = { ['name'] = 'boxville4', ['price'] = 260000, ['type'] = 'vans',  ['chest'] = '180' },
  ['burrito'] = { ['name'] = 'burrito', ['price'] = 260000, ['type'] = 'vans',  ['chest'] = '180' },
  ['burrito2'] = { ['name'] = 'burrito2', ['price'] = 245000, ['type'] = 'vans',  ['chest'] = '180' },
  ['burrito3'] = { ['name'] = 'burrito3', ['price'] = 245000, ['type'] = 'vans',  ['chest'] = '180' },
  ['burrito4'] = { ['name'] = 'burrito4', ['price'] = 40000, ['type'] = 'vans',  ['chest'] = '180' },
  ['burrito5'] = { ['name'] = 'burrito5', ['price'] = 40000, ['type'] = 'vans',  ['chest'] = '180' },
  ['gburrito'] = { ['name'] = 'gburrito', ['price'] = 40000, ['type'] = 'vans',  ['chest'] = '180' },
  ['gburrito2'] = { ['name'] = 'gburrito2', ['price'] = 80000, ['type'] = 'vans',  ['chest'] = '180' },
  ['journey'] = { ['name'] = 'journey', ['price'] = 120000, ['type'] = 'vans',  ['chest'] = '180' },
  ['minivan'] = { ['name'] = 'minivan', ['price'] = 130000, ['type'] = 'vans',  ['chest'] = '180' },
  ['minivan2'] = { ['name'] = 'minivan2', ['price'] = 140000, ['type'] = 'vans',  ['chest'] = '180' },
  ['paradise'] = { ['name'] = 'paradise', ['price'] = 160000, ['type'] = 'vans',  ['chest'] = '180' },
  ['pony'] = { ['name'] = 'pony', ['price'] = 12000, ['type'] = 'vans',  ['chest'] = '180' },
  ['pony2'] = { ['name'] = 'pony2', ['price'] = 200000, ['type'] = 'vans',  ['chest'] = '180' },
  ['rumpo2'] = { ['name'] = 'rumpo2', ['price'] = 60000, ['type'] = 'vans',  ['chest'] = '180' },
  ['rumpo3'] = { ['name'] = 'rumpo3', ['price'] = 25000, ['type'] = 'vans',  ['chest'] = '180' },
  ['speedo'] = { ['name'] = 'speedo', ['price'] = 115000, ['type'] = 'vans',  ['chest'] = '180' },
  ['speedo2'] = { ['name'] = 'speedo2', ['price'] = 32000, ['type'] = 'vans',  ['chest'] = '180' },
  ['speedo4'] = { ['name'] = 'speedo4', ['price'] = 50000, ['type'] = 'vans',  ['chest'] = '180' },
  ['surfer'] = { ['name'] = 'surfer', ['price'] = 60000, ['type'] = 'vans',  ['chest'] = '180' },
  ['surfer2'] = { ['name'] = 'surfer2', ['price'] = 150000, ['type'] = 'vans',  ['chest'] = '180' },
  ['taco'] = { ['name'] = 'taco', ['price'] = 150000, ['type'] = 'vans',  ['chest'] = '180' },
  ['youga'] = { ['name'] = 'youga', ['price'] = 150000, ['type'] = 'vans',  ['chest'] = '180' },
  ['youga2'] = { ['name'] = 'youga2', ['price'] = 150000, ['type'] = 'vans',  ['chest'] = '180' },
  ['youga3'] = { ['name'] = 'youga3', ['price'] = 150000, ['type'] = 'vans',  ['chest'] = '180' },
  --#########################################################################
  --# 𝓬𝓵𝓪𝓼𝓼𝓲𝓬_𝓬𝓪𝓻𝓼
  --#########################################################################
  ['fk8'] = { ['name'] = 'fk8', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['180sx'] = { ['name'] = '180sx', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['bmwm3gtr'] = { ['name'] = 'bmwm3gtr', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['bmwm3f80'] = { ['name'] = 'bmwm3f80', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['celta'] = { ['name'] = 'celta', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['chevroletcamarozl1'] = { ['name'] = 'chevroletcamarozl1', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['compass'] = { ['name'] = 'compass', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['dodgechargersrt'] = { ['name'] = 'dodgechargersrt', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40' },
  ['eclipse'] = { ['name'] = 'eclipse', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['eg6'] = { ['name'] = 'eg6', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['focusrs'] = { ['name'] = 'focusrs', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['fordfocusrs'] = { ['name'] = 'fordfocusrs', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['fordmustang'] = { ['name'] = 'fordmustang', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40' },
  ['hondafk8'] = { ['name'] = 'hondafk8', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['lamborghinigallardo'] = { ['name'] = 'lamborghinigallardo', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['lancerevolution9'] = { ['name'] = 'lancerevolution9', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40' },
  ['nissan370z'] = { ['name'] = 'nissan370z', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['porschemacan'] = { ['name'] = 'porschemacan', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['r33'] = { ['name'] = 'r33', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['rrghost'] = { ['name'] = 'rrghost', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['s15'] = { ['name'] = 's15', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['subaruwrx2004'] = { ['name'] = 'subaruwrx2004', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['vwjetta'] = { ['name'] = 'vwjetta', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['uptsi'] = { ['name'] = 'uptsi', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['tmfiatunot'] = { ['name'] = 'tmfiatunot', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['escort'] = { ['name'] = 'escort', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['escortrs'] = { ['name'] = 'escortrs', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['monza'] = { ['name'] = 'monza', ['price'] = 100000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  --#########################################################################
  --# 𝓵𝓾𝔁𝓾𝓻𝔂_𝓬𝓪𝓻𝓼
  --#########################################################################
  ['70camarofn'] = { ['name'] = '70camarofn', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['675lt'] = { ['name'] = '675lt', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['r820'] = { ['name'] = 'r820', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['m5f90'] = { ['name'] = 'm5f90', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['bmwm4gts'] = { ['name'] = 'bmwm4gts', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40' },
  ['bmwm8'] = { ['name'] = 'bmwm8', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['essenza'] = { ['name'] = 'essenza', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['ferrariitalia'] = { ['name'] = 'ferrariitalia', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40' },
  ['raptor2017'] = { ['name'] = 'raptor2017', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['i8'] = { ['name'] = 'i8', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['lamborghinihuracan'] = { ['name'] = 'lamborghinihuracan', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40' },
  ['mercedesa45'] = { ['name'] = 'mercedesa45', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['nissangtr'] = { ['name'] = 'nissangtr', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40' },
  ['urus'] = { ['name'] = 'urus', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['viper'] = { ['name'] = 'viper', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['p1gtr'] = { ['name'] = 'p1gtr', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['c7'] = { ['name'] = 'c7', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['911r'] = { ['name'] = '911r', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['CadesCart'] = { ['name'] = 'CadesCart', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['mercedesg65'] = { ['name'] = 'mercedesg65', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40' },
  ['mercedess63'] = { ['name'] = 'mercedess63', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['71gtx'] = { ['name'] = '71gtx', ['price'] = 150000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  --#########################################################################
  --# 𝓮𝔁𝓮𝓬𝓾𝓽𝓲𝓿𝓮_𝓬𝓪𝓻𝓼
  --#########################################################################
  ['488gtb'] = { ['name'] = '488gtb', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['audirs6'] = { ['name'] = 'audirs6', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40' },
  ['auditt'] = { ['name'] = 'auditt', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['corvettec8'] = { ['name'] = 'corvettec8', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['dodgechallenger'] = { ['name'] = 'dodgechallenger', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['ferrari458'] = { ['name'] = 'ferrari458', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['ferrari812'] = { ['name'] = 'ferrari812', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40' },
  ['fordshelby'] = { ['name'] = 'fordshelby', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['gt63'] = { ['name'] = 'gt63', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['gtr50'] = { ['name'] = 'gtr50', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['lp700r'] = { ['name'] = 'lp700r', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['mclarensenna'] = { ['name'] = 'mclarensenna', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40' },
  ['mercedesamggtr'] = { ['name'] = 'mercedesamggtr', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['nissanskyliner34'] = { ['name'] = 'nissanskyliner34', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['p1'] = { ['name'] = 'p1', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['panamera'] = { ['name'] = 'panamera', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['toyotasupra'] = { ['name'] = 'toyotasupra', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40' },
  ['veneno'] = { ['name'] = 'veneno', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['vwamarok'] = { ['name'] = 'vwamarok', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['RRazirrisa'] = { ['name'] = 'RRazirrisa', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['720s'] = { ['name'] = '720s', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['teslamodelx'] = { ['name'] = 'teslamodelx', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  ['boxster'] = { ['name'] = 'boxster', ['price'] = 200000, ['type'] = 'cars',  ['chest'] = '40', ['banned'] = true },
  --#########################################################################
  --# 𝓮𝔁𝓬𝓵𝓾𝓼𝓲𝓿𝓮_𝓿𝓮𝓱𝓲𝓬𝓵𝓮𝓼
  --#########################################################################
  ['agerars'] = { ['name'] = 'agerars', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['bugattichiron'] = { ['name'] = 'bugattichiron', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['jesko'] = { ['name'] = 'jesko', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['supragr'] = { ['name'] = 'supragr', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['bdivo'] = { ['name'] = 'bdivo', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['slamvan2'] = { ['name'] = 'slamvan2', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['bmwhommage'] = { ['name'] = 'bmwhommage', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['rs6c8'] = { ['name'] = 'rs6c8', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['teslaprior'] = { ['name'] = 'teslaprior', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['wmfenyr'] = { ['name'] = 'wmfenyr', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['frauscher16'] = { ['name'] = 'frauscher16', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['audirs7'] = { ['name'] = 'audirs7', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['rmodskyline34'] = { ['name'] = 'rmodskyline34', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['monstergt'] = { ['name'] = 'monstergt', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['monsterr'] = { ['name'] = 'monsterr', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['monsterr34'] = { ['name'] = 'monsterr34', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['sr650fly'] = { ['name'] = 'sr650fly', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['yacht2'] = { ['name'] = 'yacht2', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['rmodsianr1'] = { ['name'] = 'rmodsianr1', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['f350offroadspec'] = { ['name'] = 'f350offroadspec', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['bbdawn'] = { ['name'] = 'bbdawn', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['gcmlamboultimae'] = { ['name'] = 'gcmlamboultimae', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
  ['amggt63'] = { ['name'] = 'amggt63', ['price'] = 250000, ['type'] = 'exclusive',  ['chest'] = '40' },
   --#########################################################################
  --# VIPS
  --#########################################################################
  ['350z'] = { ['name'] = '350 Z', ['price'] = 250000, ['type'] = 'vips',  ['chest'] = '80' },
  ['acuransx'] = { ['name'] = 'Acuran SX', ['price'] = 350000, ['type'] = 'vips',  ['chest'] = '80' },
  ['astonmartindbs'] = { ['name'] = 'Aston Martin DBS', ['price'] = 350000, ['type'] = 'vips',  ['chest'] = '80' },
  ['audir8'] = { ['name'] = 'Audi R8', ['price'] = 370000, ['type'] = 'vips',  ['chest'] = '80' },
  ['aventador'] = { ['name'] = 'Aventador', ['price'] = 370000, ['type'] = 'vips',  ['chest'] = '80' },
  ['bentleybacalar'] = { ['name'] = 'Bentley Bacala R', ['price'] = 500000, ['type'] = 'vips',  ['chest'] = '80' },
  ['bloodline'] = { ['name'] = 'BloodLine', ['price'] = 370000, ['type'] = 'motovips',  ['chest'] = '80' },
  ['bmwi8'] = { ['name'] = 'BMW I8', ['price'] = 420000, ['type'] = 'vips',  ['chest'] = '80' },
  ['bmwm1wb'] = { ['name'] = 'BMW 1WB', ['price'] = 420000, ['type'] = 'vips',  ['chest'] = '80' },
  ['bmwm4gts'] = { ['name'] = 'BMW M4 GTS', ['price'] = 450000, ['type'] = 'vips',  ['chest'] = '80' },
  ['bmwm5e34'] = { ['name'] = 'BMW M5 E34', ['price'] = 450000, ['type'] = 'vips',  ['chest'] = '80' },
  ['bugattiatlantic'] = { ['name'] = 'Bugatti Atlantic', ['price'] = 480000, ['type'] = 'vips',  ['chest'] = '80' },
  ['camaro'] = { ['name'] = 'Camaro', ['price'] = 400000, ['type'] = 'vips',  ['chest'] = '80' },
  ['civictyper'] = { ['name'] = 'Civic Type R', ['price'] = 300000, ['type'] = 'vips',  ['chest'] = '80' },
  ['corvettec7'] = { ['name'] = 'Corvette C7', ['price'] = 430000, ['type'] = 'vips',  ['chest'] = '80' },
  ['dodgecharger1970'] = { ['name'] = 'Dodge Charger 1970', ['price'] = 410000, ['type'] = 'vips',  ['chest'] = '80' },
  ['dodgechargerrt69'] = { ['name'] = 'Dodge Charger RT69', ['price'] = 425000, ['type'] = 'vips',  ['chest'] = '80' },
  ['dodgechargersrt'] = { ['name'] = 'Dodge Charger SRT', ['price'] = 415000, ['type'] = 'vips',  ['chest'] = '80' },
  ['escalade2021'] = { ['name'] = 'Escalade 2021', ['price'] = 315000, ['type'] = 'vips',  ['chest'] = '80' },
  ['escaladegt900'] = { ['name'] = 'Escalade GT900', ['price'] = 365000, ['type'] = 'vips',  ['chest'] = '80' },
  ['ferrarif12'] = { ['name'] = 'Ferrari F12', ['price'] = 290000, ['type'] = 'vips',  ['chest'] = '80' },
  ['ferrarif40'] = { ['name'] = 'Ferrari F40', ['price'] = 365000, ['type'] = 'vips',  ['chest'] = '80' },
  ['golfgti'] = { ['name'] = 'Golf GTI', ['price'] = 200000, ['type'] = 'vips',  ['chest'] = '80' },
  ['golfmk7'] = { ['name'] = 'Golf MK7', ['price'] = 180000, ['type'] = 'vips',  ['chest'] = '80' },
  ['jeepcherokee'] = { ['name'] = 'Jeep Cherokee', ['price'] = 280000, ['type'] = 'vips',  ['chest'] = '80' },
  ['lancerevolutionx'] = { ['name'] = 'Lancer Evolution X', ['price'] = 380000, ['type'] = 'vips',  ['chest'] = '80' },
  ['m8competition'] = { ['name'] = 'M8 Competition', ['price'] = 340000, ['type'] = 'vips',  ['chest'] = '80' },
  -- ['maverick2'] = { ['name'] = 'Maverick 2', ['price'] = 340000, ['type'] = 'vips',  ['chest'] = '80' },
  ['mazdarx7'] = { ['name'] = 'Mazda RX7', ['price'] = 400000, ['type'] = 'vips',  ['chest'] = '80' },
  ['mazdarx72'] = { ['name'] = 'Mazda RX72', ['price'] = 410000, ['type'] = 'vips',  ['chest'] = '80' },
  ['mercedesamg63'] = { ['name'] = 'Mercedes AMG 63', ['price'] = 510000, ['type'] = 'vips',  ['chest'] = '80' },
  ['mercedesg65'] = { ['name'] = 'Mercedes G65', ['price'] = 500000, ['type'] = 'vips',  ['chest'] = '80' },
  ['mercedesgt63'] = { ['name'] = 'Mercedes GT63', ['price'] = 490000, ['type'] = 'vips',  ['chest'] = '80' },
  ['mustang1969'] = { ['name'] = 'Mustang 1969', ['price'] = 460000, ['type'] = 'vips',  ['chest'] = '80' },
  ['mustangfast'] = { ['name'] = 'Mustang Fast', ['price'] = 560000, ['type'] = 'vips',  ['chest'] = '80' },
  ['nissangtr2'] = { ['name'] = 'Nissan GTR 2', ['price'] = 560000, ['type'] = 'vips',  ['chest'] = '80' },
  ['nissangtr3'] = { ['name'] = 'Nissan GTR 3', ['price'] = 600000, ['type'] = 'vips',  ['chest'] = '80' },
  ['nissangtr50'] = { ['name'] = 'Nissan GTR 50', ['price'] = 650000, ['type'] = 'vips',  ['chest'] = '80' },
  ['nissangtrnismo'] = { ['name'] = 'nissangtrnismo', ['price'] = 350000, ['type'] = 'vips',  ['chest'] = '80' },
  ['panameramansory'] = { ['name'] = 'Panamera Mansory', ['price'] = 550000, ['type'] = 'vips',  ['chest'] = '80' },
  ['porsche911'] = { ['name'] = 'Porsche 911', ['price'] = 570000, ['type'] = 'vips',  ['chest'] = '80' },
  ['r1'] = { ['name'] = 'R1', ['price'] = 400000, ['type'] = 'motovips',  ['chest'] = '40' },
  ['r6'] = { ['name'] = 'R6', ['price'] = 450000, ['type'] = 'motovips',  ['chest'] = '40' },
  ['rangerover'] = { ['name'] = 'Range Rover', ['price'] = 490000, ['type'] = 'vips',  ['chest'] = '80' },
  ['s1000rr'] = { ['name'] = 'S1000 RR', ['price'] = 490000, ['type'] = 'motovips',  ['chest'] = '40' },
  ['shelbygt500'] = { ['name'] = 'Shelby GT500', ['price'] = 370000, ['type'] = 'vips',  ['chest'] = '80' },
  ['silvias15'] = { ['name'] = 'Silvia S15', ['price'] = 420000, ['type'] = 'vips',  ['chest'] = '80' },
  ['skyliner34'] = { ['name'] = 'Skyline R34', ['price'] = 420000, ['type'] = 'vips',  ['chest'] = '80' },
  ['skyliner342'] = { ['name'] = 'Skyline R342', ['price'] = 470000, ['type'] = 'vips',  ['chest'] = '80' },
  ['subarubrz'] = { ['name'] = 'Subaru BRZ', ['price'] = 400000, ['type'] = 'vips',  ['chest'] = '80' },
  ['subaruimpreza'] = { ['name'] = 'Subaru Impreza', ['price'] = 430000, ['type'] = 'vips',  ['chest'] = '80' },
  ['subaruimpreza'] = { ['name'] = 'Subaru Impreza', ['price'] = 430000, ['type'] = 'vips',  ['chest'] = '80' },
  ['toyotasupra2'] = { ['name'] = 'Toyota Supra 2', ['price'] = 380000, ['type'] = 'vips',  ['chest'] = '80' },
  ['urbandevil'] = { ['name'] = 'Urban Devil', ['price'] = 360000, ['type'] = 'motovips',  ['chest'] = '80' },
  ['vwtouareg'] = { ['name'] = 'VW Touareg', ['price'] = 300000, ['type'] = 'vips',  ['chest'] = '80' },


  --#########################################################################
  --# 𝓬𝓾𝓼𝓽𝓸𝓶𝓼_𝓫𝓲𝓴𝓮𝓼
  --#########################################################################
  ['tiger'] = { ['name'] = 'tiger', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['tiger1200'] = { ['name'] = 'tiger1200', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['africat'] = { ['name'] = 'africat', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['xj6'] = { ['name'] = 'xj6', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['xt660vip'] = { ['name'] = 'xt660vip', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['zx6r'] = { ['name'] = 'zx6r', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['PCX'] = { ['name'] = 'PCX', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['harleydavidsonfx'] = { ['name'] = 'harleydavidsonfx', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['harleydavidsonrg'] = { ['name'] = 'harleydavidsonrg', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['hondacbr650r'] = { ['name'] = 'hondacbr650r', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['f800'] = { ['name'] = 'f800', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['r1200'] = { ['name'] = 'r1200', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  -- ['r6'] = { ['name'] = 'r6', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['h2carb'] = { ['name'] = 'h2carb', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  ['z1000'] = { ['name'] = 'z1000', ['price'] = 50000, ['type'] = 'bikes',  ['chest'] = '40' },
  --#########################################################################
  --# work
  --#########################################################################
  ['towtruck'] = { ['name'] = 'towtruck', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['ambulance'] = { ['name'] = 'ambulance', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['g63amg6x6cop'] = { ['name'] = 'g63amg6x6cop', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['a45policia'] = { ['name'] = 'a45policia', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['amarokpolicia'] = { ['name'] = 'amarokpolicia', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['policiacb500'] = { ['name'] = 'policiacb500', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['mercedesgle'] = { ['name'] = 'mercedesgle', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['jeeppolicia'] = { ['name'] = 'jeeppolicia', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['m8comando'] = { ['name'] = 'm8comando', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['mercedespolicia'] = { ['name'] = 'mercedespolicia', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['mercxclass'] = { ['name'] = 'mercxclass', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['paramedicoheli'] = { ['name'] = 'paramedicoheli', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['r820p'] = { ['name'] = 'r820p', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['annihilator'] = { ['name'] = 'annihilator', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['police2'] = { ['name'] = 'police2', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['polmav'] = { ['name'] = 'polmav', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['police3'] = { ['name'] = 'police3', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['dinghy'] = { ['name'] = 'dinghy', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['dinghy2'] = { ['name'] = 'dinghy2', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['dinghy3'] = { ['name'] = 'dinghy3', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['dinghy4'] = { ['name'] = 'dinghy4', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['cg160'] = { ['name'] = 'cg160', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['coachrv'] = { ['name'] = 'coachrv', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['golg9'] = { ['name'] = 'golg9', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['hauler'] = { ['name'] = 'hauler', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['Kart3'] = { ['name'] = 'Kart3', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['Kart20'] = { ['name'] = 'Kart20', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['Kart26'] = { ['name'] = 'Kart26', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['Kart65'] = { ['name'] = 'Kart65', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['Kart73'] = { ['name'] = 'Kart73', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['taxi'] = { ['name'] = 'taxi', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['pbus'] = { ['name'] = 'pbus', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['bus'] = { ['name'] = 'bus', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['airbus'] = { ['name'] = 'airbus', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['coach'] = { ['name'] = 'coach', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['6x6ev'] = { ['name'] = '6x6ev', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['gstlp700xv2'] = { ['name'] = 'gstlp700xv2', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['killerhwak'] = { ['name'] = 'killerhwak', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['rmodgtr50'] = { ['name'] = 'rmodgtr50', ['price'] = -1, ['type'] = 'work',  ['chest'] = '200' },
  ['trash'] = { ['name'] = 'Caminhao do lixo', ['price'] = -1, ['type'] = 'work',  ['chest'] = 40 },
  ['ratloader'] = { ['name'] = 'Lenhador', ['price'] = -1, ['type'] = 'work',  ['chest'] = 40 },
  ['flatbed'] = { ['name'] = 'Guincho', ['price'] = -1, ['type'] = 'work',  ['chest'] = 40 },

  }